# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Natsume"
license = "MIT"
licenselink = "https://github.com/notyim/natsume/blob/master/LICENSE.md"
description = "Port of Natsume theme for hugo"
homepage = "http://blog.noty.im/"
tags = ["noty.im", "axcoto.com", "simple", "minimal"]
features = ["responsive", "syntax", "highlight"]
min_version = 0.13

[author]
  name = "kureikain"
  homepage = "https://axcoto.com"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
